//key bindings, all should be lowercase letters
#define MOVL '1'
#define MOVR '2'
#define ROTA '3'
#define DROP '4'
#define RSET '5'
#define SNXT '6'
#define STXT '7'
#define EXT  '8'
#define TPLS '9'
